global:
  scrape_interval:     15s
  evaluation_interval: 15s


alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
        
rule_files:
  - 'rules.yml'

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: MyIP
    static_configs:
      - targets: ['192.168.1.244:9182']