apiVersion: v1
kind: ConfigMap
metadata:
  name: config-files
  namespace: default
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['alertmanager-service:9093']
    rule_files:
      - 'rules.yml'
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
            labels:
              instance: 'prometheus'
      - job_name: MyIP
        static_configs:
          - targets: ['192.168.99.1:9182']
            labels:
              instance: 'myip'
  rules.yml: |-
    groups:
    - name: cpu_alerts
      rules:
      - alert: HighCpuUsage
        expr: (100 * sum by (instance)(rate(windows_cpu_time_total{instance=~"myip|prometheus",mode=~"user|privileged"}[1m])) / 300) * 100 > 20
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU Usage Detected in {{ $labels.instance }}"
          description: "The instance {{ $labels.instance }}: CPU usage is above 20% for at least 2 minutes."
    - name: instance_Down
      rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "The instance {{ $labels.instance }} is down."

          